- [完整源码](https://github.com/yuyeqianxun/yuyeqianxun.github.io/blob/master/promise/myPromise.js)
- [Promise A+ 中文翻译](https://github.com/yuyeqianxun/yuyeqianxun.github.io/blob/master/promise/Promise%20A+%20中文翻译.md)
- [附带测试，图一乐](https://github.com/yuyeqianxun/yuyeqianxun.github.io/blob/master/promise/package.json)
> 建议结合Promise A+规范查看本文

# Promise

对照 promise a+规范实现

根据规范 2.1，Promise 拥有三个状态

```js
const PENDING = "pending";
const FULFILLED = "fulfilled";
const REJECTED = "rejected";
```

根据规范 2.2，2.3 以及 Promise 的用法，可以定义出 Promise 函数的大体框架。

```js
// new Promise((resolve, reject) => {
//     resolve(1);
// })
function myPromise(fn) {}

myPromise.prototype.then = function (onFulfilled, onRejected) {};

function resolveProcedure(promise2, x) {}
```

根据规范 2.1 下的内容，我们可以写出 Promise 主函数

```js
function myPromise(fn) {
  let _this = this;
  _this.state = PENDING;
  _this.value = null;
  _this.reason = null;
  function resolve(value) {
    if (_this.state === PENDING) {
      _this.state = FULFILLED;
      _this.value = value;
    }
  }

  function reject(reason) {
    if (_this.state === PENDING) {
      _this.state = REJECTED;
      _this.reason = reason;
    }
  }
  fn(resolve, reject);
  //fn = (resolve, reject) => {
  //     resolve(1);
  //}
  //立马执行fn函数，并且传入resolve, reject为参数
}
```

但是这里有个问题，fn 可能会报错(比如 fn 本事就是个 bug)，一旦报错，Promise 将无法继续执行，所以我们需要捕获 fn 可能的报错

```js
function myPromise(fn) {
  //...
  try {
    fn(resolve, reject);
  } catch (e) {
    reject(e); //一旦捕获报错，进入reject函数，改变Promise状态
  }
}
```

根据规范 2.2.1，我们需要对 onFulfilled 和 onRejected 作处理

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  onFulfilled = typeof onFulfilled === "function" ? onFulfilled : null;
  onRejected = typeof onFulfilled === "function" ? onFulfilled : null;
};
```

但是处理并没有结束，onFulfilled 或 onRejected 赋值了 null，接下来该怎么办呢？

看规范 2.2.5，onFulfilled 或 onRejected 要被调用，就必须是一个函数；规范 2.2.7.3 和 2.2.7.4 则描述了当 onFulfilled 或 onRejected 不是函数时，我们需要将值传给 promise2。

所以，当 onFulfilled 或 onRejected 不是函数，我们就需要将它们转化为函数，这样它们就能作为函数被调用，也能传递给 promise2，改造一下。

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  let _this = this;
  onFulfilled =
    typeof onFulfilled === "function" ? onFulfilled : () => this.value; //在此，你传入的onFulfilled会忽略，被赋值为一个函数，函数返回promise的value能被传递给promise2(值穿透)
  onRejected =
    typeof onRejected === "function" ? onRejected : () => this.reason; //同上
};
```

回到之前

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  //...
  if (_this.state === FULFILLED) {
    //2.2.2
    onFulfilled();
  } else if (_this.state === REJECTED) {
    //2.2.3
    onRejected();
  } else {
    //pending态
  }
};
```

再看 2.2.4 以及注解 3.1，我们发现 onFulfilled 或 onRejected 必须异步调用

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  //...
  if (_this.state === FULFILLED) {
    //2.2.2
    setTimeout(onFulfilled);
  } else if (_this.state === REJECTED) {
    //2.2.3
    setTimeout(onRejected);
  } else {
    //pending态
  }
};
```

那如果 Promise 一直处于 pending 怎么办呢？

```js
let p = new myPromise((resolve, reject) => {
  setTimeout(() => resolve(1), 1000);
});
p.then((res) => {
  console.log(res);
  return res * 2;
})
  .then((data) => {
    console.log(data);
    return data * 4;
  })
  .then((fin) => {
    console.log(fin);
    return fin * 6;
  });
```

比如以上的例子，当进入 then 方法的时候，Promise 需要等 setTimeout 执行完才能执行 then。
并且根据 2.2.6，我们需要按顺序将多个 then 里的回调执行。

```js
function myPromise(fn) {
  //...
  _this.resolveCbs = []; //将then或者catch里的回调函数存起来
  _this.rejectCbs = [];
  //状态改变，开始执行resolve
  function resolve(value) {
    if (_this.state === PENDING) {
      _this.state = FULFILLED;
      _this.value = value;
      _this.resolveCbs.forEach((cb) => cb(_this.value)); //当Promise进入FULFILLED，执行回调函数,回调函数的参数为Promise当前的value
    }
  }

  function reject(reason) {
    if (_this.state === PENDING) {
      _this.state = REJECTED;
      _this.reason = reason;
      _this.rejectCbs.forEach((cb) => cb(_this.reason));
    }
  }
}
myPromise.prototype.then = function (onFulfilled, onRejected) {
  //...
  if (_this.state === FULFILLED) {
    //2.2.2
    setTimeout(onFulfilled);
  } else if (_this.state === REJECTED) {
    //2.2.3
    setTimeout(onRejected);
  } else {
    //pending态
    setTimeout(() => {
      _this.resolveCbs.push(onFulfilled);
      _this.rejectCbs.push(onRejected);
    });
  }
};
```

接下来就到了 2.2.7：

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  //...
  return new myPromise();
};
```

接下来就到了 2.2.7.1 和 2.2.7.2，根据要求改造一下：

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  //...
  if (_this.state === FULFILLED) {
    //2.2.2
    setTimeout(() => {
      try {
        //2.2.7.2
        let x = onFulfilled();
        resolveProcedure(promise2, x);
      } catch (e) {
        reject(e);
      }
    });
  } else if (_this.state === REJECTED) {
    //2.2.3
    setTimeout(onRejected);
  } else {
    //pending态
    setTimeout(() => {
      _this.resolveCbs.push(onFulfilled);
      _this.rejectCbs.push(onRejected);
    });
  }
};
```

这里就发现了问题，promise2 和 reject 都为定义，之前返回了一个 Promise，啥也没干，正好用上。

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  //...
  let promise2;
  if (_this.state === FULFILLED) {
    //2.2.2
    promise2 = new myPromise((resolve, reject) => {
      setTimeout(() => {
        try {
          //2.2.7.2
          let x = onFulfilled(_this.value);
          resolveProcedure(promise2, x);
        } catch (e) {
          reject(e);
        }
      }, 0);
    });
  } else if (_this.state === REJECTED) {
    //2.2.3
    promise2 = new myPromise((resolve, reject) => {
      setTimeout(() => {
        try {
          //2.2.7.2
          let x = onRejected(_this.reason);
          resolveProcedure(promise2, x);
        } catch (e) {
          reject(e);
        }
      }, 0);
    });
  } else {
    //pending态
    promise2 = new myPromise((resolve, reject) => {
      _this.resolveCbs.push(() => {
        setTimeout(() => {
          try {
            //2.2.7.2
            let x = onFulfilled(_this.value);
            resolveProcedure(promise2, x);
          } catch (e) {
            reject(e);
          }
        }, 0);
      });
      _this.rejectCbs.push(() => {
        setTimeout(() => {
          try {
            //2.2.7.2
            let x = onRejected(_this.reason);
            resolveProcedure(promise2, x);
          } catch (e) {
            reject(e);
          }
        }, 0);
      });
    });
  }
};
```

到此，then 的规范就写完了。
接下来就是 Promise 兼容程序。
首先是 2.3.1

```js
function resolveProcedure(promise2, x) {
  if (promise2 === x) {
    reject(throw TypeError("出错了"));
  }
}
```

出师未捷身先死，刚写完就发现，我们还没有 reject 函数呢，我们需要从 then 中传入，当然 resolve 也有一同传入

```js
myPromise.prototype.then = function (onFulfilled, onRejected) {
  //...
  promise2 = new myPromise((resolve, reject) => {
    setTimeout(() => {
      try {
        //2.2.7.2
        let x = onFulfilled();
        resolveProcedure(promise2, x, resolve, reject);
      } catch (e) {
        reject(e);
      }
    }, 0);
  });
};
function resolveProcedure(promise2, x, resolve, reject) {
  if (promise2 === x) {
    reject(new TypeError("出错了"));
  }
}
```

接下来看 2.3.2、2.3.3、2.3.4，但是 2.3.2 其实是在 2.3.3 中的，Promise 就是一个对象，并且有 then 方法，2.3.3 更多可能是指 thenable

```js
function resolveProcedure(promise2, x, resolve, reject) {
  //...
  if ((x && typeof x === "object") || typeof x === "function") {
  } else {
    resolve(x); //2.3.4
  }
}
```

2.3.4 已解决，接下来看 2.3.3 的细则

```js
function resolveProcedure(promise2, x, resolve, reject) {
  //...
  if ((x && typeof x === "object") || typeof x === "function") {
    try {
      //2.3.3.2
      let then = x.then; //2.3.3.1
      if (typeof then === "function") {
        then.call(x); //2.3.3.3
      } else {
        resolve(x); //2.3.3.4
      }
    } catch (e) {
      reject(e);
    }
  } else {
    resolve(x); //2.3.4
  }
}
```

大部分已经完成了，接下来只需要完成 2.3.3.3 的细则就可以。2.3.3.3 是一个 then 方法，这里 then 的两个参数分别为 resolvePromise 和 rejectPromise，并且只能执行一次，还会影响 catch 执行,需要加一个锁。

```js
function resolveProcedure(promise2, x, resolve, reject) {
  //...
  let lock = false;
  if ((x && typeof x === "object") || typeof x === "function") {
    try {
      //2.3.3.2
      let then = x.then; //2.3.3.1
      if (typeof then === "function") {
        then.call(x,y=>{
          if (lock) return;
          lock = true;
          resolveProcedure(promise2, y, resolve, reject)//2.3.3.3.1
        },r=>{
          if (lock) return;
          lock = true;
          reject(r)//2.3.3.3.2
        }); //2.3.3.3
      } else {
        if (lock) return;
        lock = true;
        resolve(x); //2.3.3.4
      }
    } catch (e) {
      if (lock) return;
      lock = true;
      reject(e);
    }
  } else {
    resolve(x); //2.3.4
  }
}
```

至此，promise就已经实现了
